openapi: 3.0.0
info:
  title: Category Module
  version: 1.0.0
paths:
  /category/categoryCountList:
    get:
      summary: Get category statistics
      description: Returns statistics for all categories
      operationId: getCategoryCountList
      tags:
        - Category Management
      responses:
        "200":
          description: Category statistics retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryCount"
        "500":
          description: Internal server error

components:
  schemas:
    Category:
      type: object
      description: Blog category information
      required:
        - id
        - name
        - pid
        - description
        - status
        - createTime
        - updateTime
        - delFlag
      properties:
        id:
          type: integer
          format: int64
          description: Category ID
          example: 1
        name:
          type: string
          description: Category name
          example: "Technology"
        pid:
          type: integer
          format: int64
          description: Parent category ID (-1 indicates no parent category)
          example: -1
        description:
          type: string
          description: Category description
          example: "Technical articles"
        status:
          type: string
          description: Category status (0 for normal, 1 for disabled)
          example: "0"
        createBy:
          type: integer
          format: int64
          description: Creator ID
          example: 1001
        createTime:
          type: string
          format: date-time
          description: Creation time
          example: "2024-02-12T10:00:00Z"
        updateBy:
          type: integer
          format: int64
          description: Updater ID
          example: 1002
        updateTime:
          type: string
          format: date-time
          description: Update time
          example: "2024-02-12T12:00:00Z"
        delFlag:
          type: integer
          description: Deletion flag (0 for not deleted, 1 for deleted)
          example: 0

    CategoryCount:
      type: object
      description: Category statistics information
      required:
        - name
        - count
      properties:
        name:
          type: string
          description: Category name
          example: "Technology"
        count:
          type: integer
          format: int32
          description: Number of articles in the category
          example: 42