spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/golemon_blog
    username: root
    password: mysql
  devtools:
    restart:
      enabled: false

  mvc:
    log-request-details: true

  jackson:
    serialization:
      indent_output: true

  main:
    allow-circular-references: true # Allow circular dependencies TODO unsafe

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    redis:
      port: 6379
      password: redis
      host: localhost
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter: TRACE
    org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod: TRACE
    org.springframework.web.servlet.DispatcherServlet: TRACE


mybatis:
  mapper-locations: classpath*:mapper/*.xml
mybatis-plus:
  global-config:
    db-config:
      id-type: auto # Global ID type is auto-increment
  mapper-locations: "classpath*:/mapper/**/*.xml" # Mapper.xml file location, this is the default value.
# Enable SQL logging
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

deepseek:
  api:
    key: <api_key>
    url: https://api.deepseek.com/v1/chat/completions
    model: deepseek-chat
    temperature: 0.7
    max-tokens: 2000
